services:
  app:
    build:
      context: .
      target: dev # Change this to 'prod' for production
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # To avoid overwriting node_modules with the host
    environment:
      NODE_ENV: development # Change to 'production' if building with the 'prod' target

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
