services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app/src
      - ../config/development.env:/app/.env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - my-network

  app-prod:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app/src
      - ../config/production.env:/app/.env
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000" # Pourquoi c'est different de l'autre en haut ?
    networks:
      - my-network

networks:
  my-network:
    driver: bridge